# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Audrey
tagline:          'Engineering Blog-ish'
description:      'Learning along the way.'
url:              https://audity.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Plugins from https://jashmehta3300.github.io/making-your-own-blog/
plugins: [jekyll-paginate, jekyll-gist, redcarpet]

